import { useEffect, useMemo, useState } from 'react'
import { createShopifyCart, isDemo, loadProducts } from './shopify.js'

function money(n,c='PHP'){try{return new Intl.NumberFormat('en-PH',{style:'currency',currency:c,maximumFractionDigits:0}).format(n)}catch{return `${c} ${n}`}}
function App(){
 const [products,setProducts]=useState([]),[cart,setCart]=useState([]),[cartOpen,setCartOpen]=useState(false),[filter,setFilter]=useState('All'),[query,setQuery]=useState(''),[notice,setNotice]=useState(''),[nav,setNav]=useState(false)
 useEffect(()=>{loadProducts().then(setProducts)},[])
 const types=['All',...new Set(products.map(p=>p.type))]
 const shown=useMemo(()=>products.filter(p=>(filter==='All'||p.type===filter)&&`${p.title} ${p.type} ${p.color}`.toLowerCase().includes(query.toLowerCase())),[products,filter,query])
 const total=cart.reduce((s,x)=>s+x.price*x.qty,0), count=cart.reduce((s,x)=>s+x.qty,0)
 function add(p){setCart(c=>{const hit=c.find(x=>x.variantId===p.variantId);return hit?c.map(x=>x.variantId===p.variantId?{...x,qty:x.qty+1}:x):[...c,{...p,qty:1}]});setCartOpen(true)}
 function qty(id,n){setCart(c=>c.map(x=>x.variantId===id?{...x,qty:n}:x).filter(x=>x.qty>0))}
 async function checkout(){ if(!cart.length)return; if(isDemo){setNotice('Demo checkout: connect Shopify in .env to create a real checkout.');return} try{const created=await createShopifyCart(cart); if(created?.checkoutUrl) location.href=created.checkoutUrl}catch(e){setNotice(e.message)} }
 return <div className="store">
  <div className="announcement"><span>FREE METRO MANILA SHIPPING OVER ₱3,000</span><span>NEW / STUDIO 02 AVAILABLE NOW</span></div>
  <header><a className="logo" href="#">STREET<span>LAB</span></a><nav className={nav?'open':''}><a href="#shop">Shop</a><a href="#new">New arrivals</a><a href="#journal">Journal</a><a href="#about">About</a></nav><div className="head-actions"><button onClick={()=>document.querySelector('.search input')?.focus()}>SEARCH</button><button onClick={()=>setCartOpen(true)}>BAG <b>{String(count).padStart(2,'0')}</b></button><button className="hamb" onClick={()=>setNav(v=>!v)}>☰</button></div></header>
  <main>
   <section className="hero"><div className="hero-text"><span>STUDIO 02 / 2026</span><h1>Built for the<br/><em>in-between.</em></h1><p>Everyday pieces for work, movement, and everything after. Designed in Manila with a quiet utility mindset.</p><a href="#shop">Shop the collection <b>→</b></a></div><div className="hero-visual"><div className="poster"><span>STREETLAB®</span><strong>02</strong><small>MANILA / PH</small></div><div className="shape one"/><div className="shape two"/><div className="vertical">ESSENTIALS FOR DAILY MOTION</div></div></section>
   <section className="marquee"><span>UTILITY</span><i>✦</i><span>COMFORT</span><i>✦</i><span>FORM</span><i>✦</i><span>MANILA</span><i>✦</i></section>
   <section className="shop" id="shop"><div className="shop-head"><div><small>01 / SHOP</small><h2>Current rotation</h2></div><p>A compact uniform of dependable layers, easy proportions, and useful objects.</p></div><div className="toolbar"><div className="filters">{types.slice(0,6).map(t=><button className={filter===t?'active':''} key={t} onClick={()=>setFilter(t)}>{t}</button>)}</div><label className="search">⌕ <input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search products"/></label></div><div className="product-grid">{shown.map((p,i)=><article key={p.id}><div className="product-image"><img src={p.image} alt={p.title}/><span>{String(i+1).padStart(2,'0')}</span><button onClick={()=>add(p)}>ADD +</button></div><div className="product-info"><div><h3>{p.title}</h3><p>{p.type} / {p.color}</p></div><strong>{money(p.price,p.currency)}</strong></div></article>)}</div></section>
   <section className="split" id="journal"><div className="manifesto"><small>02 / PROCESS</small><h2>Less noise.<br/>More <em>wear.</em></h2><p>StreetLab is a fictional commerce brand built as a portfolio demonstration of a custom React storefront connected to Shopify.</p><a href="#shop">Read the design notes →</a></div><div className="lookbook"><span>LOOK 04</span><div className="figure"><i/><b/></div><strong>THE COMMUTE SET</strong></div></section>
  </main>
  <footer id="about"><div className="logo inverse">STREET<span>LAB</span></div><div><strong>Portfolio storefront</strong><p>React + Shopify Storefront API</p></div><div><strong>Location</strong><p>Manila, Philippines</p></div><span>© 2026 STREETLAB DEMO</span></footer>
  <aside className={`cart ${cartOpen?'open':''}`}><div className="cart-head"><div><small>YOUR BAG</small><h2>{count} {count===1?'item':'items'}</h2></div><button onClick={()=>setCartOpen(false)}>×</button></div><div className="cart-lines">{cart.length===0?<div className="empty"><span>○</span><strong>Your bag is empty.</strong><p>Add something from the current rotation.</p></div>:cart.map(x=><div className="cart-line" key={x.variantId}><img src={x.image}/><div><strong>{x.title}</strong><span>{x.color}</span><div className="qty"><button onClick={()=>qty(x.variantId,x.qty-1)}>−</button><b>{x.qty}</b><button onClick={()=>qty(x.variantId,x.qty+1)}>+</button></div></div><em>{money(x.price*x.qty,x.currency)}</em></div>)}</div><div className="cart-foot"><div><span>Subtotal</span><strong>{money(total,cart[0]?.currency||'PHP')}</strong></div><button className="checkout" disabled={!cart.length} onClick={checkout}>Checkout <span>↗</span></button><small>Taxes and shipping calculated at checkout.</small>{notice&&<p className="notice">{notice}</p>}</div></aside>{cartOpen&&<div className="shade" onClick={()=>setCartOpen(false)}/>} 
 </div>
}
export default App
